version: '3.7'

services:
  app:
    image: app_flights:v2
    container_name: app_flights
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    env_file:
      - .env
    ports: 
      - 80:3000
    depends_on:
      - mongodb
      - rabbitmq
    restart: always
    networks:
      - ms_nestjs

  microservice-flights:
    image: microservice_flights:v2
    container_name: microservice_flights
    build:
      context: ./flights-microservice
      dockerfile: Dockerfile
    env_file:
      - .env
    depends_on:
      - mongodb
      - rabbitmq
    restart: always
    networks:
      - ms_nestjs

  microservice-passengers:
    image: microservice_passengers:v2
    container_name: microservice_passengers
    build:
      context: ./passenger-microservice
      dockerfile: Dockerfile
    env_file:
      - .env
    depends_on:
      - mongodb
      - rabbitmq
    restart: always
    networks:
      - ms_nestjs

  microservice-users:
    image: microservice_users:v2
    container_name: microservice_users
    build:
      context: ./user-microservice
      dockerfile: Dockerfile
    env_file:
      - .env
    depends_on:
      - mongodb
      - rabbitmq
    restart: always
    networks:
      - ms_nestjs

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    expose:
      - 5672
      - 15672
    restart: always
    networks:
      - ms_nestjs

  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - mongodb:/data/db
    expose:
      - 27017
    networks:
      - ms_nestjs

volumes:
  mongodb:


networks:
  ms_nestjs:
